name: Currency Bot Scheduler

on:
  schedule:
    - cron: "0 * * * *"   # run every hour
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml pytz

      - name: Run Currency Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_IDS: ${{ secrets.CHAT_IDS }}
          CHANNEL_LINK: ${{ secrets.CHANNEL_LINK }}
        run: python sarrafi_bot.py
